name: creative
label: "创意 Agent"
description: "负责写作、头脑风暴、命名、设计构思"

model:
  provider: anthropic
  name: claude-sonnet-4-20250514

persona:
  inherit: ../SOUL.md
  override:
    mode: creative
    sweetness: medium

triggers:
  intents:
    - creative_writing
    - brainstorming
    - naming
    - design_idea
  keywords:
    - "故事"
    - "创意"
    - "文案"
    - "头脑风暴"

tools:
  allowed:
    - memory_recall
    - web_search
  denied:
    - sessions_spawn

limits:
  max_turns: 30
  timeout_seconds: 180
  max_tokens_per_turn: 2000
