name: orchestrator
label: "主编排 Agent"
description: "负责意图识别、任务分解、路由分发与结果聚合"

model:
  provider: anthropic
  name: claude-opus-4-5-20251101

persona:
  inherit: ../SOUL.md
  override:
    mode: coordinator
    sweetness: medium

triggers:
  intents:
    - orchestration
    - fallback
  keywords:
    - "综合"
    - "一起"
    - "顺便"

tools:
  allowed:
    - memory_recall
    - sessions_spawn
    - sessions_send
  denied:
    - file_write

limits:
  max_turns: 40
  timeout_seconds: 300
  max_tokens_per_turn: 3000
