FROM node:22-bookworm

RUN corepack enable

WORKDIR /workspace

COPY . /workspace

ENV NODE_ENV=production

ARG SAVC_RUNTIME_SKIP_CHOWN="0"
RUN if [ "${SAVC_RUNTIME_SKIP_CHOWN}" != "1" ]; then chown -R node:node /workspace; fi

USER node
