#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

export PATH="${HOME}/.local/bin:${PATH}"

ENV_FILE="${REPO_ROOT}/config/.env.local"
OPENCLAW_CONFIG="${HOME}/.openclaw/openclaw.json"
OPENCLAW_SUBMODULE="${REPO_ROOT}/openclaw"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
else
  echo "[ERROR] Missing ${ENV_FILE}" >&2
  echo "Create it with: cp config/.env.example config/.env.local" >&2
  exit 1
fi

if [[ ! -f "${OPENCLAW_CONFIG}" ]]; then
  echo "[ERROR] Missing ${OPENCLAW_CONFIG}" >&2
  echo "Run setup first: bash scripts/setup.sh" >&2
  exit 1
fi

if [[ ! -d "${OPENCLAW_SUBMODULE}" ]]; then
  echo "[ERROR] Missing OpenClaw submodule at: ${OPENCLAW_SUBMODULE}" >&2
  echo "Run: git submodule update --init --recursive" >&2
  exit 1
fi

if ! command -v pnpm >/dev/null 2>&1; then
  echo "[ERROR] pnpm not found in PATH." >&2
  echo "Enable with Corepack (recommended): corepack enable && corepack prepare pnpm@latest --activate" >&2
  exit 1
fi

# OpenClaw uses OPENCLAW_GATEWAY_PORT (docs: --port > OPENCLAW_GATEWAY_PORT > gateway.port > default 18789)
export OPENCLAW_GATEWAY_PORT="${OPENCLAW_PORT:-18789}"

# Ensure a local token exists when gateway.auth.token uses env substitution in ~/.openclaw/openclaw.json
if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    OPENCLAW_GATEWAY_TOKEN="$(openssl rand -hex 16)"
  else
    OPENCLAW_GATEWAY_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
  fi
  export OPENCLAW_GATEWAY_TOKEN

  if grep -q '^OPENCLAW_GATEWAY_TOKEN=' "${ENV_FILE}"; then
    sed -i "s/^OPENCLAW_GATEWAY_TOKEN=.*/OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}/" "${ENV_FILE}"
  else
    {
      echo ""
      echo "# Auto-generated by scripts/dev.sh (local-only)"
      echo "OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}"
    } >> "${ENV_FILE}"
  fi
fi

# Keep OpenClaw CLI usable outside this repo by syncing the token to ~/.openclaw/.env.
OPENCLAW_GLOBAL_ENV="${HOME}/.openclaw/.env"
mkdir -p "${HOME}/.openclaw"
touch "${OPENCLAW_GLOBAL_ENV}"
chmod 600 "${OPENCLAW_GLOBAL_ENV}" 2>/dev/null || true
if grep -q '^OPENCLAW_GATEWAY_TOKEN=' "${OPENCLAW_GLOBAL_ENV}"; then
  sed -i "s/^OPENCLAW_GATEWAY_TOKEN=.*/OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}/" "${OPENCLAW_GLOBAL_ENV}"
else
  {
    echo ""
    echo "# Auto-generated by SAVC scripts (local-only)"
    echo "OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}"
  } >> "${OPENCLAW_GLOBAL_ENV}"
fi

# Note: upstream `pnpm gateway:watch` can get stuck if a watch rebuild deletes `dist/entry.js`
# during a Node `--watch` restart. We run the equivalent watch pipeline but disable cleaning.
pnpm -C "${OPENCLAW_SUBMODULE}" exec tsdown --no-clean
pnpm -C "${OPENCLAW_SUBMODULE}" exec tsdown --watch --no-clean &
COMPILER_PID=$!

cleanup() {
  kill "${COMPILER_PID}" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

cd "${OPENCLAW_SUBMODULE}"
node --watch openclaw.mjs gateway --force
