#!/usr/bin/env bash
set -euo pipefail

export PATH="${HOME}/.local/bin:${PATH}"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/config/.env.local"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    OPENCLAW_GATEWAY_TOKEN="$(openssl rand -hex 16)"
  else
    OPENCLAW_GATEWAY_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
  fi
  export OPENCLAW_GATEWAY_TOKEN

  if [[ -f "${ENV_FILE}" ]]; then
    if grep -q '^OPENCLAW_GATEWAY_TOKEN=' "${ENV_FILE}"; then
      sed -i "s/^OPENCLAW_GATEWAY_TOKEN=.*/OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}/" "${ENV_FILE}"
    else
      {
        echo ""
        echo "# Auto-generated by scripts/openclaw.sh (local-only)"
        echo "OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}"
      } >> "${ENV_FILE}"
    fi
  fi
fi

# Keep OpenClaw CLI usable outside this repo by syncing the token to ~/.openclaw/.env.
OPENCLAW_GLOBAL_ENV="${HOME}/.openclaw/.env"
mkdir -p "${HOME}/.openclaw"
touch "${OPENCLAW_GLOBAL_ENV}"
chmod 600 "${OPENCLAW_GLOBAL_ENV}" 2>/dev/null || true
if grep -q '^OPENCLAW_GATEWAY_TOKEN=' "${OPENCLAW_GLOBAL_ENV}"; then
  sed -i "s/^OPENCLAW_GATEWAY_TOKEN=.*/OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}/" "${OPENCLAW_GLOBAL_ENV}"
else
  {
    echo ""
    echo "# Auto-generated by SAVC scripts (local-only)"
    echo "OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}"
  } >> "${OPENCLAW_GLOBAL_ENV}"
fi

exec openclaw "$@"
